title: Baptiste Maingret's Homepage
email: baptiste.maingret@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website I started during my training in data sciences.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bmaingret.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bmaingret
name: "Baptiste Maingret"
repository: "bmaingret/bmaingret.github.io"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-149004210-1"
    anonymize_ip: true

google_site_verification : "ehG0k64s7-KvuTjVq2RKWYoDUV9_QijOcKairEqC0lA"

# Build settings
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

  # minimal-mistakes customization
remote_theme: "mmistakes/minimal-mistakes"

timezone: Europe/Paris

minimal_mistakes_skin: "air"

search: true

include: 
  - _pages
exclude:
  - Gemfile
  - tmp
keep_files:
  - .git



encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

author:
        name: "Baptiste Maingret"
        avatar: "/assets/images/bio-photo.webp"
        bio: "French engineer with a strong interest in data and machine learning.
        I also like travelling and guitars and in general any ***-**engineering."
        location: "Marseille, France"
        links:
                - label: "Linkedin"
                  icon: "fab fa-fw fa-linkedin"
                  url: "https://linkedin.com/in/baptistemaingret"
                - label: "GitHub"
                  icon: "fab fa-fw fa-github"
                  url: "https://github.com/bmaingret"


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

 
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      classes: wide
      excerpt_separator: <!--more-->
      show_date: true
      read_time: true
      permalink: /blog/:year-:month-:day-:title

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
  - scope:
      path: "assets/cv/*.pdf"
    values:
      sitemap: false
